Notas do livor "Clean Code" de Robert Martin
* Cap 2 - Nomes significativos
** Usar nomes que revelem seu propósito
	Nomes devem demonstrar seu propósito. Devem responder as grandes questões:
      - porque existe?
      - o que faz?
      - como é usado?
** Evite informações erradas
   1) Não se refira a um grupo de contas como accountList, a menos que realmente seja uma List.
   2)  Mesmo se for uma lista é melhor não colocar o tipo no nome
** Faça distinções significativas 
	Palavras muito comuns são outra forma de distinção que nada expressam. Imagine que você tenha uma classe Product. Se houver uma outra chamada ProductInfo ou ProductData, você usou nomes distintos que nada revelam de diferente. Info e Data são palavras muito comuns e vagas.

	O nome de uma 'tabela' jamais deve conter a palavr 'tabela'. Então como NameString é melhor do que "Name"? Um "Name" pode ser um número do tipo ponto flutuante? Caso possa, estaria violando uma regra de passar informações incorretas. Imagine que você encontre uma classe Customer e outra CustomerObject. O que a diferença nos nomes lhe diz? Qual seria a melhor para possuir o histório de pagamento de um cliente?

	Conhecemos um aplicativo que é assim - abaixo está exatamente o tipo de erro:
      getActiveAccount();
      getActiveAccounts();
      getActiveAccountInfo();

	Na ausência de convenções específicas, não há como distinguir 'moneyAmount' de 'money', 'customerInfo' de 'customer', 'accountData' de 'account' e 'theMessage' de 'message'. Faça distinção de nomes de uma forma que o leitor compreenda as diferenças
** Nomes de Classes e Objetos
	Classes e objetos devem ter nomes com substantivo(s), como Customer, WikiPage, Account e AddressParser. Evite palavras como Gerente, Processador Dados ou Info no nome de uma classe, que também não deve ser um verbo.
** Nomes de métodos
	Os nomes de métodos devem ter verbos, como Post Payment, Delete Page ou Save. Devem-se nomear métodos de acesso, alteração e autenticação segundos seus valores e adicionar os prefixos get, set ou is de acordo como o padrão javabean.
** Use nomes a partir do Domínio da Solução
	Lembre-se de que serão programadores que lerão seu código. Portanto, pode usar termos de Informática, nomes de algoritmos, nomes de padrões, temos matemáticos etc. Não é prudente pensar num nome a partir do domínio do problema, pois não queremos que nossos companheiros de trabalho tenham de consultar o cliente toda hora para saber o significado de um nome o qual eles já conhecem o conceito, só que por outro nome.
	O nome AccountVisitor ("conta do visitante") significa o bastante para um programador familiarizado com o padrão VISITOR. Qual programador não saberia o que é uma JobQueue ("fila de tarefas")? Há muitas coisas técnicas que os programadores devem fazer. Selecionar nomes técnicos para tais coisas é, geralmente, o método mais adequado.
** Contextos
*** Adicione um Contexto Significativo
	Há poucos nomes que são significativos por si só - a maioria não é. Por conta disso, você precisa usar nomes que façam parte do contexto do leitor. Para isso vocÊ os coloca em classes, funções e namespaces bem nomeados. Se nada disso funcionar, então talvez como último recurso seja necessário adicionar prefixos ao nome.
	Imagine que você tenha variáveis chamadas firstName, lastName, street, houseNumber, city, state, zipcode. Vistas juntas, fica bem claro que elas formam um endereço. Mas e se você só visse a variável state sozinha num método? Automaticamente você assumiria ser parte de um endereço?
	Podem-se usar prefixos para adicionar um contexto: addrFirstName, addrLastName, addrState etc. Pelo menos os leitores entenderão que essas variáveis são parte um uma estrutura maior. É claro que uma melhor solução seria criar uma classe chamada Address. Então, até o compilador sabe que as variáveis pertencem a um escopo maior.
*** Não Adicione Contextos Desnecessários
	Em um aplicativo fictício chamado "Gas Station Deluxe" (GSD), seria uma péssima ideia adicionar prefixos a todas classe com GSD. Para ser sincero, você estará trabalhando contro suas ferramentas. Você digita G e pressiona a tecla para autocompletar e recebe uma lista quilométrica de cada classe no sistema. Isso é inteligente? Para que dificultar a ajuda da IDE?
	Da mesma forma, digamos que você inventou uma classe MailingAddress no módulo de contabilidade do GSD e que o chamou de GSDAccountAddress. mais tarde, você precisa armazenar um endereço postal de seu cliente no aplicativo. Você usaria GSDAccountAddress? Parece que o nome é adequado? Dez dos 17 caracteres são redundantes ou irrelevantes.
	Nomes curtos geralmente são melhores contanto que sejam claros. *Não adicione mais contexto a um nome do que o necessário.*]
	Os nomes accountAddress e customerAdress estão bons para instâncias da classe Address, mas seriam ruins para nomes de classes. Address está bom para uma classe. Se precisar diferenciar entre endereço MAC, enderço de portas e endereços da Web, uma ideia seria PostalAddress, MAC e URI. Os nomes resultantes são mais precisos, motivo esse da tarefa de se atribuir nomes.
** Geral
Prefira nomes de uma única letra SÓ quando usados como variáveis locais dentro de métodos pequenos. *O tamanho de um nome deve ser proporcional ao tamanho do escopo*.
* Cap 3 - Funções 
** Pequenas!
A primeira regra para funções é que elas devem ser pequenas. Elas devem ter no máximo 20 linhas. As funções devem ter duas, ou três, ou quatro linhas.
** Blocos e Identação
	Blocos dentro de instruções if, else, while devem ter apenas 1 linha. Possivelmente uma chamada de função. Além de manter a função 	pequena, isso adiciona um valor significativo, pois a função chamada de dentro do blco pode receber um nome descritivo.
	Isso também implica que as funções não devem ser grandes e ter estruturas aninhadas. Portanto, o nível de identação de uma função deve ser de, no máximo, um ou dois.
** Faça Apenas uma Coisa
	AS FUNÇÕES DEVEM FAZER UMA COISA. DEVEM FAZÊ-LA BEM. DEVEM FAZER APENAS ELA.
	O problema dessa declaração é que é difícil saber o que é "uma coisa". A Listagem 3-3 (pg 35, citada abaixo) faz uma coisa?

#+BEGIN_SRC java
	public static String renderPageWithSetupsAndTeardowns(PageData pageData,  boolean isSuite) throws Exception {
		if (isTestPage(pageData))
			includeSetupAndTearDownPages(pageData, isStuite);
		return pageData.getHtml();
#+END_SRC

	É fácil dizer que ela faz três:
	1. Determina se a página é de teste
	2. Se for, inclui SetUps e TearDowns
	3. Exibe a página em HTML

	Então, qual é? A função está fazendo uma ou três coisas? Note que os três passos da função estão em um nível de abstração abaixo do nome da função. Podemos descrever a função com um breve parágrafo TO:
	
		TO RenderPageWithSetupsAndTeardowns, verificamos se a página é de teste, se for, incluímos setups e teardowns. Em ambos os casos, exibimos a página em HTML.

	Se uma função faz apenas aqueles passos em um nível abaixo do nome da função, então ela está fazendo uma só coisa. Apesar de tudo, o motivo de criarmos função é para decompor um conceito maior (em outras palavras, o nome da função) em uma série de passos no próximo nível de abstração.
	Ficaria muito difícil reduzir a Listagem 3-3 de modo significativo. Poderíaomos colocar a instrução if numa função chamada includeSetupsAndTeardownsIfTestPage, mas isso simplesmente reformula o código, sem modificar o nível de abstração.
	Portanto, uma forma de saber se uma função faz mais de "uma coisa" é se você pode extrair outra função dela a partir de seu nome que não seja apenas uma reformulação de sua implementação.
** Use Nomes Descritivos
	Não tenha medo de criar nomes extensos, pois eles são melhores do que um pequeno e enigmático. Um nome longo e descritivo é melhor do que um comentário extenso e descritivo. Use uma convenção de nomenclatura que possibilite uma fácil leitura de nomes de funçõoes com várias palavras e, então, use estas para dar à função um nome que explique o que ela faz.
** Parâmetros Lógicos
	Esses parâmetros são feios. Passar um booleano para um função certamente é uma prátic horrível, pois ele complica imediatamente a assinatur do método, mostrando explicitamente que a função faz mais de uma coisa. Ela faz uma coisa se o valor for verdadeiro, e outra se for falso.
** Verbos e Palavras-Chave
	Escolher bons nomes para funções pode ir desde explicar o propósito da função à ordem a finalidade dos parâmetros. No caso de uma mônade, a função e o parâmetro devem formar um belo par verbo/substantivo. Por exemplo, write(name) é bastante claro. Seja o que for esse 'nome', ele será 'escrito'.  Um nome ainda melhor seria writeField(name), que nos diz que 'nome' é um 'campo'.
	Este último é um exemplo do formato palavra-chave do nome de uma função. Ao usar este formato codificamos os nomes dos parâmetros no nome da função. Por exemplo, pode ser melhor escrever asserEquals do que assertExpectedEqualsActual(expected, actual), o que resolveria o problema de ter de lembrar a ordem dos parâmetros.
** Parâmetros de Saída
	Os parâmetros são comumente interpretados como entradas de uma função. Se já usa o programa há alguns anos, estou certo de que você já tece de voltar e ler novamente um parâmetro que era, na verdade, de saída, e não de entrada. Por exemplo:

		appendFooter(s);

	Essa função anexa s como rodapé (Footer, em inglês) em algo? Ou anexa um rodapé a s? O s é uma entrada ou uma saída? Não precisa olhar muito a assinatura da função para ver:

		public void appendFooter(StringBuffer report)

	Isso esclarece a questão, mas à custa da verificação da declaração da função. Qualquer coisa que lhe force a verificar a assinatura da função é equivalente a uma releitura. Isso é uma interrupção do raciocínio e deve ser evitado.
	Antes do surgimento da programação orientada a objeto, às vezes era preciso ter parâmetros de saída. Entretanto, grande parte dessa necessidade sumiu nas linguagens OO, pois o propósito de this é servir como parâmetro de saída. Em outras palavras, seria melhor invocar appendFooter como:
	
		report.appendFooter();

	De modo geral, devem-se evitar parâmetros de saída. Caso sua função precise alterar o estado de algo, faça-a mudar o estado do objeto a que pertence.
** Tratamento de erro é uma coisa só
	As funções devem fazer uma coisa só. Tratamento de erro é uma coisa só. Portanto, uma função que trata de erros não deve fazer mais nada. Isso implica que a palavra try está dentro de uma função e deve ser a primeira instrução e nada mais deve vir após os blocos catch/finally.
* Cap 4 - Comentários
** Evite o comentário se é possível usar uma função ou uma variável
	Considere o pedaço de código abaixo:
		
		// o módulo da lista global <mod> depende do
		// subsistema do qual fazemos parte?
		if (smodule.getDependSubsystems().contains(subSysMod.getSubSystem()))

	Poderia-se evitar o comentáio e usar:
		
		ArrayList moduleDependees = smodule.getDependSynsystems();
		String outSubSystem = subSysMod.getSubSystem();
		if (moduleDependees.contains(ourSubsystem))
* Cap 5 - Formatação
** Distância vertical
	Os conceitos intimamente relacionados devem ficar juntos verticalmente. Obviamente essa regra não funciona para conceitos em arquivos separados. Mas, então, não se devem separar em arquivos distintos conceitos intimamente relacionados, a menos que tenha uma razão muito boa. Na verdade, esse é um dos motivos por que se devem evitar variáveis protegidas.
	Para os conceitos que são tão intimamente relacionados e que estão no mesmo arquivo-fonte, a separação vertical deles deve ser uma medida do quão importante eles são para a inteligibilidade um do outro. Queremos evitar que nossos leitores tenham de ficar visualizando vários dos nossos arquivos-fonte e classes.
*** Funções dependentes
Se uma função chama outra, elas devem ficar verticalmente próximas, e a que chama deve ficar acima da que for chamada, se possível. Isso dá um fluxo natural ao programa. Se essa convenção for seguida a fim de legibilidade, os leitores poderão confiar que as declarações daquelas funções virão logo em seguida após seu uso.

* Cap 6 - Objetos e Estruturas de Dados
** Conclusão 
	Os objetos expõem as ações e ocultam os dados. Isso facilita a adição de novo tipos de objetos sem precisar modificar as ações existentes e dificulta a inclusão de novas atividades em objetos existentes. As estrutras de dados expõem os dados e não possuem ações significativas. Isso facilita a adição de novas ações às estruturas de dados existentes e dificulta a inclusão de novas estruturas de dados em funções existentes.
	Em um dado sistema, às vezes, desejaremos flexibilidade para adicionar novos tipos de dados, e, portanto, optaremos por objetos. Em outras ocasiões, desejaremos querer flexibilidade para adicionar novas ações, e, portanto optaremos por tipos de dados e procedimentos.
* Cap 7 - Tratamento de Erros
** Use exceções não verificadas
As exceções verificadas podem às vezes ser úteis se você estiver criando uma biblioteca crítica: é preciso capturá-las. Mas no desenvolvimento geral de aplicativo, os custos da dependência superam as vantagens.
* Cap 8 - Limites
	Entender código de terceiros é difícil. Integrá-lo ao seu também é. Fazer ambos ao mesmo tempo dobra a dificuldade. E se adotássemos uma outra abordagem? Em vez de experimentar e temtar o novo código, poderíamos criar testes para explorar nosso conhecimento sobre ele. Jim Newkirk chama isso de testes de aprendizagem.
	Nesses testes, chamamos a API do código externo como faríamos ao usá-la em nosso aplicativo. Basicamente estaríamos controlando os experimentos que verificam nosso conhecimento daquela API. O teste se focaliza no que desejamos saber sobre a API.
* Cap 9 - Testes de Unidade
** As três leis do TDD
	Hoje em dia todos sabem que o TDD nps pede para criar primeiro os testes de unidade antes do código de produção. Mas essa regra é apenas o início. Considere as três leis abaixo:
	1a Lei) Não se deve escrever o código de produção até criar um teste de unidade de falhas.
	2a Lei) Não se deve escrever mais de um teste de unidade do que o necessário para falhar, e não compilar é falhar.
	3a Lei) Não se deve escrever mais códigos de produção do que o necessário para aplicar o teste de falha atual.
	
	Os testes e o código de produção são escritos juntos, com os testes apenas alguns segundos mais adiantados.
** Testes limpos
	O que torna um teste limpo? Três coisas: legibilidade, legibilidade e legibilidade. Talvez isso seja até mais importante nos testes de unidade do que no código de produção. O que torna os testes legíveis? O mesmo que torna todos os códigos legíveis: clareza, simplicidade e consistência de expressão. Num teste você quer dizer muito com o mínimo de expressões possíveis.
* Cap 10 - Classes
** As classes devem ser pequenas!
	A primeira regra para classes é que devem ser pequenas. Assim como as funções, ser pequena também é a regra principal quando o assunto for criar classes.
	Com as funções medimos o tamanho contando as linhas físicas. Com as classes usamos uma medida diferente. Contamos responsabilidades.
	O nome da uma classe deve descrever quais responsabilidades ela faz. Na verdade, selecionar um nome é a primeira forma de ajudar a determinar o tamanho da classe. Se não derivamos um nome conciso para ela, então provavelmente ela ficará grande. Quanto mais ambíguo for o nome da classe, maiores as chances de ela ficar com muitas responsabilidades. Por exemplo, nomes de classes que possuam palavras de vários sentidos, como Processor ou Manager ou Super, geralmente indicam um acúmulo lastimável de responsabilidades.
	Devemos também poder escrever com cerca de 25 palavras uma breve descrição da classe, sem usar as palavras "se", "e", "ou" ou "mas". Como descreveríamos a SuperDashboard? "A SuperDashboard oferce acesso ao componente que foi o último utilizado e também nos permite acompanhar os números da versão e da compilação". O primeiro "e" é uma dica de que a classe possui responsabilidades em excesso.
** O Princípio da Responsabilidade Única
	O Princípio da Responsabilidade Única  (SRP, sigla em inglês para Sigle Responsability Principle) afirma que uma classe ou módulo deve ter um, e apneas um, motivo para mudar. Este princípio nos dá uma definição de responsabilidade e uma orientação para o tamanho da classe. Estas devem ter apenas uma responsabilidade e um motivo para mudar.
	Desejamos que nossos sistemas sejam compostos por muitas classes pequenas, e não poucas classes grandes. Cada classe pequena encapsula uma única responsabilidade, possui um único motivo para ser alterada e contribui com poucas outras para obter os comportamentos desejados no sistema.
* Cap 13 - Concorrência
** Cuidado com dependências entre métodos sincronizados
	Dependências entre métodos sincronizados causam pequenos bugs no código concorrente. A linguagem Java possui a palavra chave synchonized, que protege um único método. Entretanto, se houver mais de um método sincronizado na mesma classe compartilhada, então seu sistema pode ser sido escrito incorretamente.

	Recomendação: Evite usar mais de um método em um objeto compartilhado.

	Haverá vezes em que você deverá usar mais de um método em um objeto compartilhado. Neste caso, há três formas de deixar o código certo:
*** Bloqueio voltado para o cliente
Faça o cliente bloquear o servidor antes de chamar o primeiro método e certifique-se de que o bloqueio inclua o código que chama o último método
*** Bloqueio voltado para o servidor
Dentro do servidor, crie um método que bloqueie o servidor, chame todos os métodos e, então, desbloqueie. Faça o cliente chamar o novo método.
*** Servidor extra
Crie um servidor intermediário que efetue o bloqueio. Esse é um exemplo de bloqueio voltado para o servidor, no qual o servidor original não pode ser alterado.
** Primeiro, faça com que seu código sem thread funcione
Isso pode parecer óbvio, mas não custa nada repetir. Certifique-se de que o código funcione sem threads. Geralmente, isso significa criar POJOs que são chamados pelas suas threads. Os POJOs não enxergam as threads e, portanto, podem ser testados fora do ambiente com threads. Quando mais locais no seu sistema você conseguir colocar POJOs, melhor.

Recomendação: Não procure bugs não relacionados a threads com os relacionados a elas ao mesmo tempo. Certifique-se de que seu código funcione sem threads.
* Cap 16 - Refatorando o SerialDate
** final (pg 276)
Também exclui a palavra reservada 'final' das declarações de parâmetros e variáveis. Até onde pude entender, ela não adicionava nenhum valor real, só adiciona mais coisas aos restos inúteis. Eliminar essas 'final' contraria alguns conhecimentos convencionais, Por exemplo, Robert Simons nos aconselha a "... colocar final e, todo o seu código". Obviamente, eu discordo. Acho que há alguns poucos usos para o final, como a constante 'final', mas fora isso, as palavras reservadas acrescentam pouca coisa e criam muito lixo. Talvez eu me sinta dessa forma porque os tipos de erros que 'final' possa capturar, os testes de unidade que escrevi já capturam.
* Exemplos de código
** pg 278 - parse String -> Object
#+BEGIN_SRC java
public static Month parse(String s) {
s = s.trim();
for (Month m : Month.values())
	if (m.matches(s))
		return m;

throw new IllegalArgumentException(String.format("%s is not a valid mont
#+END_SRC

** pg 282 - mover switch para enum
#+BEGIN_SRC java
public enum DateInterval {
	OPEN {
		public boolean isIn(int d, int left, int right) {
			return d > left && d < right;
		}

	},
	CLOSED_LEFT {
		public boolean isIn(int d, int left, int right) {
			return d >= left && d < right;
		}
	},
	CLOSED_RIGHT {
		public boolean isIn(int d, int left, int right) {
			return d > left && d <= right;
		}
	},
	CLOSED {
		public boolean isIn(int d, int left, int right) {
			return d >= left && d <= right;
		}
	};

	public abstract boolean isIn(int d, int left, int right);
}

#+END_SRC

* Code smells
** F1: Parâmetros em excesso
	As funções devem ter um número pequeno de parâmetros. Ter nenhum é melhor. Depois vem um, dois, três. Mais do que isso é questionável e deve-se evitar com preconceito.
** F2: Parâmetros de saída
	Os parâmetros de saída são inesperados. Os leitores esperam que parâmetros sejam de entrada, e não de saída. Se sua função deve alterar o estado de algo, faça-a mudar o do objeto no qual ela é chamada.
** F3: Parâmetros lógicos
	Parâmetros booleanos explicitamente declaram que a função faz mais de uma coisa. Eles são confusos e se devem eliminá-los.
** F4: Função morta
	Devem-se descartar os métodos que nunca são chamados. Manter pedaços de código morto é devastador. Não tenha receio de excluir a função. Lembre-se de que seu sistema de controle de código fonte ainda se lembrará dela.
** G3: Comportamento incorreto nos limites
	Parece óbvio dizer que o código deva se comportar corretamente. O problema é que raramente percebemos como é complicado um comportamento correto. Desenvolvedores geralmente criam funções as quais eles acham que funcionarão e, então, confiam em suas intuições em vez de se esforçar para provar que o código funciona em todos os lugares e limites.
	Não existe substituição para uma dedicação minuciosa. Cada condição de limite, cada canto do código, cada ajuste e exceção representa algo que pode estragar um algoritmo elegante e intuitivo. Não dependa da sua intuição. Cuida de cada condição de limite e crie testes para cada.
** G5: Duplicação
	Essa é uma das regras mais importantes neste livro, e você deve levá-la muito a sério. Praticamente, todo autor que escreve sobre projetos de software a mencionam. Dave Thomas e Andy Hunt a chamaram de princípio DRY (Don´t Repeat Yourself - Não se Repita), o qual Kent Beck tornou o centro dos princípios da eXtreme Programming (XP) e o chamou de "Uma vez, e apenas uma". Ron Jeffries colocou essa como a segunda regra, sendo a primeira aquela em que se deve fazer todos os testes passarem com êxito.
	Sempre que você vir duplicação em código, isso significa que você perdeu uma chance para abstração. Aquela duplicação provavelmente poderia se tornar uma sub-rotina ou talvez outra classe completa. Ao transformar a duplicação em tal, você aumenta o vocabulário da linguagem de seu projeto. Outros programadores podem usar os recursos de abstração que você criar. E a codificação se torna mais rápida e menos propensa a erros devido a você ter elevado o nível de abstração.
	A forma mais óbvia de duplicação é quando você possui blocos de código idênticos, como se alguns programadores tivessem saído copiando e colando o mesmo código várias vezes. Estes devem ser substituídos por métodos simples.
	Una forma mais sutil seriam as estruturas aninhadas de switch/case e if/else que aparecem repetidas vezes em diversos módulos, sempre testando as mesmas condições. Nesse caso, deve-se substituir pelo polimorfismo.
	Formas ainda mais sutil seriam os módulos que possuem algoritmos parecidos, mas que não possuem as mesmas linhas de código. Isso ainda é duplicação e deveria-se resolvê-la através do padrão TEMPLATE METHOD ou STRATEGY.
	Na verdade, a maioria dos padrões de projeto que têm surgido nos últimos 15 anos são simplesmente maneiras bem conhecidas para eliminar a duplicação. Assim como as regras de normalização (Normal Forms) de Codd são uma estratégia para eliminar a duplicação em banco de dados. A OO em si - e também a programação estruturada - é uma tática para organizar módulos e eliminar a duplicação.
	Acho que a mensagem foi passada: encontre e elimine duplicações sempre que puder.
** G8: Informações excessivas
	Módulos bem definidos possuem interfaces pequenas que lhe permite fazer muito com pouco. Já os mal definidos possuem interfaces grandes e longas que lhe obriga a usar muitas formas diferentes para efetuar coisas simples. Uma interface bem definida não depende de muita funções, portanto, há baixo acoplamento. E uma interface mal definida depende de diversas funções que devem ser chamadas, gerando um alto acoplamento.
	Bons desenvolvedores de software aprendem a limitar o que expõem nas interfaces de suas classes e módulos. Quanto menos métodos tiver uma classe, melhor. Quanto menos variáveis uma função usar, melhor. Quanto menos variáveis tiver uma classe, melhor.
	Esconda seus dados. Esconda suas funções utilitárias. Esconda suas constantes e suas variáveis temporárias. Não crie classes com muitos métodos ou variáveis de instâncias. Não crie muitas variáveis e funções protegidas para suas subclasses. Concentre-se em manter as interfaces curtas e muito pequenas. Limite as informações para ajudar a manter um baixo acoplamento.
** G10: Separação vertical
	Devem-se declarar as variáveis e funções próximas de onde são usadas. Devem-se declarar as variáveis locais imediatamente acima de seu primeiro uso, e o escopo deve ser vertical. Não queremos que variáveis locais sejam declaradas centenas de linhas afastadas de onde são utilizadas.
	Devem-se declarar as funções privadas imediatamente abaixo de seu primeiro uso. Elas pertencem ao escopo de toda a classe. Mesmo assim, ainda desejamos limitar a distância vertical entre as chamadas e as declarações. Encontrar uma função privada deve ser uma questão de buscar para baixo a partir de seu primeiro uso.
** G11: Inconsistência
	Se você fizer algo de uma determinada maneira, faça da mesma forma todas as outras coisas similares. Isso retoma o princípio da surpresa mínima. Atenção ao escolher suas convenções. Uma vez escolhidas, atente para continuar seguindo-as.
	Se dentro de uma determinada função você usa uma variável de nome response para armazenar uma HttpServletResponse, então use o mesmo nome da variável de nome consistente nas outras funções que usem os objetos HttpServletResponse. Se chamar um método de processVerificationRequest, então use um nome semelhante, como processDeletionRequest para métodos que processem outros tipos de pedidos (request).
	Uma simples consitência como essa, quando aplicada corretamente, pode facilitar muito mais a leitura e a modificação do código.
** G19: Use variávies descritivas
	Uma das formas mais poderosas de tornar um programa legível é separar os cálculos em valors intermediários armazenados em variáveis com nomes descritivos.
	Mais variáveis explicativas geralmente são melhores do que menos. É impressionante como um módulo opaco pode repentinamente se tornar transparente simplesmente ao separar os cálculos em valores intermediários bem nomeados.
** G20: Nomes de funções devem dizer o que elas fazem
	Veja este código:

		Date newDate = date.add(5);

	Você acha que ele adiciona cinco dias à data? Ou seria a semanas, ou horas? A instância date mudou ou a função simplesmente retornou uma nova Date sem alterar a antiga? Não dá para saber a partir da chamada o que a função faz.
	Se a função adiciona cinco dias à data e a altera, então ela deveria se chamae addDaysTo ou increaseByDays. Se, por outro lado, ela retorna uma nova data acrescida de cinco dias, mas não altera a instância date, ela deveroa se chamar daysLater ou daysSince.
	Se você tiver de olhar a implementação (ou a documentação) da função para saber o que ela faz, então é melhor selecionar um nome melhor ou reorganizar a funcionalidade de modo que esta possa ser colocada em funções com nomes melhores.
** G25: Substitua os números mágicos por constantes com nomes
	De modo geral, é um péssima ideia ter números soltos em seu código. Deve-se escondê-los em constantes com nomes bem selecionados.
	O termo "Número Mágico" não se aplica apenas a números, mas também a qualquer token (símbolo, termos, expressões, números, etc) que possua um valor que não seja auto-explicativo.
** G26: Seja preciso
	Quando você toma uma decisão em seu código, certifique-se de fazê-la precisamente. Saiba por que a tomou e como você lidará com quaisquer exceções. Não seja desleixado com a precisão de suas decisões. Se decidir chamar uma função que retorne null, certifique-se de verificar por null. Se for consultar o que você acha ser o únivo registro no banco de dados, garanta que seu código verifique se não há outros. Se precisar lidar com concorrência, use inteiros (ou, melhor ainda, uma classe Money que use inteiros) e lide apropriadamente com arrendondamento. Se houver a possibilidade de atualização concorrente, certifique-se de implementar algum tipo de mecanismo de bloqueio.
	Ambiguidades e imprecisão em códigos são resultado de desacordos ou desleixos. Seja qual for o caso, elas devem ser eliminadas.
** G28: Encapsule as condicionais
	A lógica booleana já é difícil o bastante de entender sem precisar vê-la  no contexto de um if ou um while. Extraia funções que expliquem o propósito da estrutura condicional.
	Por exemplo:
	
		if (shouldBeDeleted(timer))

	é melhor do que

		if (timer.hasExpired() && !timer.isRecurrent())
** G30: As funções devem fazer uma coisa só
	Costuma ser tentador criar funções que tenham várias seções que efetuam uma série de operações. Funções desse tipo fazem amis de uma coisa, e devem ser divididas em funções melhores, cada uma fazendo apenas uma coisa.
	Por exemplo:
#+BEGIN_SRC java
	public void pay() {
		for (Employee e: employees) {
			if (e.isPayday()) {
				Money pay = e.calculatePay();
				e.delivererPay(pay);
			}
		}
	}
#+END_SRC

	Esse pedaço de código faz três coisas. Ele itera sobre todos os funcionários, verifica se cada um deve ser pago e, então, paga o funcionário. Esse código ficaria melhor assim:

#+BEGIN_SRC java
	public void pay() {
		for (Employee e: employees) {
			payIfNecessary(e);
		}
	}

	private void payIfNecessary(Employee e) {
            if (e.isPayday()) {
			calculateAndDeliverPay(e); 
		}
	}

	private void calculateAndDeliverPay(Employee e)
            Money pay = e.calculatePay();
            e.delivererPay(pay);
    }
#+END_SRC
	
	Cada uma dessas funções faz apenas uma coisa.
** G33: Encapsule as condições de limites
	Condições de limite são difíceis de acompanhar. Coloque o processamento para elas em um único lugar. Não as deixe espalhadas pelo código. Não queremos um enxame de +1s e -1s aparecendo aqui e acolá. Considere o exemplo abaixo do FIT:
#+BEGIN_SRC java
	if (level + 1 < tags.length) 
	{
		parts = new Parse(body, tags, level + 1, offset + endTag);
		body = null;
	}
#+END_SRC

	Note que 'level + 1' aparece duas vezes. Essa é uma condição de limite que deveria estar encapsulada dentro de uma variável com um nome ou algo como nextLevel.
#+BEGIN_SRC java
	int nextLevel = level + 1;
	if (nextLevel < tags.length) 
	{
		parts = new Parse(body, tags, nextLevel, offset + endTag);
		body = null;
	}
#+END_SRC
** G36: Evite a navegação transitiva	
	De modo geral, não queremos que um único módulo saiba tudo sobre seus colaboradores. Mais especificamente, se A colabora com B e B colabora com C, nã queremos que os módulos que usem A enxerguem C. (Por exemplo, não queremos a.getB().getC().doSomething();.)
	Isso às vezes se chama de Lei de Demeter. Os programadores pragmáticos chamam de "Criar um Código Tímido". Em ambos casos, resume-se a se garantir que os módulos saibam sobre seus colaboradores imediatos apenas e não sobre o mapa de navegação de todo o sistema.
	Se muitos módilos usam algum tipo de instrução a.getB().getC(), então seria difícil alterar o projeto e a arquitetura para introduzir um Q entre B e C. Seria preciso encontrar cada instância de a.getB().getC() e converter para a.getB().getQ().getC(). É assim que as estruturas se tornam rígidas. Módulos em excesso enxergam demais sobre a arquitetura.
	Em vez diso, queremos que nossos colaboradores imediatos ofereçam todos os serviços de que precisamos. Não devemos ter de percorrer a planta do sistema em busca do módulo que desejamos chamar, mas simplesmente ser capaz de dizer:
		meuColaborador.facaAlgo().
** N1: Escolha nomes descritivos
	Não se apresse ao escolher um nome. Certifique-se de que seja desctitivo. Lembre-se de que os sentidos tendem a se perder conforme o software evolui. Portanto, reavalie frequentemente a adequação dos nomes que você escolher.
	Essa não é apenas uma recomendação para lhe "satisfazer". Nomes em softwares são 90% responsáveis pela legibilidade do software. Você precisa tomar seu tempo para escolhê-los sabiamente e mantê-los relevantes. Nomes são muito importantes para serem tratados de qualquer jeito.
** N7: Nomes devem descrever os efeitos colaterais
	Nomes devem descrever tudo o que uma função, variável ou classe é ou faz. Não oculte os efeitos colaterais com um nome. Não use um simples verbo para descrever uma função que faça mais do que uma mera ação. Por exemplo, considere o código abaixo do TestNG:

#+BEGIN_SRC java
	public ObjectOutputStream getOos() throws IOException {
		if (m_oos == null) {
			m_oos = new ObjectOutputStream(m_socket.getOutputStream());
		}
		return m_oos;
	}
#+END_SRC
	
	Essa função faz um pouco mais além de pegar um "oos", ela cria o "oos" se ele não tiver sido criado ainda. Logo, um nome melhor seria createOrReturnOos.
** T6: Teste abundantemente bugs próximos	
	Bugs tendem a se reunir. Quando encontrar um bug numa função, é sábio fazer um teste exaustivo nela. Provavelmente você verá que o bug não estava só.
