apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app     #ref 01: esse cara tem que ter o mesmo nome que o ref 02
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
  replicas: 6
  selector:
    matchLabels:
      app: nginx-app     #ref 02: esse cara tem que ter o mesmo nome que o ref 01

